### ISSUE TITLE
Initial requirements

### ISSUE THREAD

**Issue by anxiousmodernman** [anxiousmodernman/hpt#1]
Meta issue for the initial build-out. Pick an unchecked item and open an issue for it, or edit the list of unchecked items yourself.

## Configuration

Probably want to start with environment variables for everything, and maybe a ".dotfile" later.

* DO_SECRET_ACCESS_KEY
* DO_ACCESS_KEY
* AWS_SECRET_ACCESS_KEY
* AWS_ACCESS_KEY

## Internal plumbing

* [ ] Consistently capture stdout, stderr of subprocesses
* [ ] Think "engine". We are executing a complicated data structure.

## Config Language Compiler

The config file format will be declarative, with some string mapping for resolvers or variables.

* [ ] be able to follow imports, resequence configs 
* ~merge multiple files - we will probably have a tree? a list of lists?~
* ~build a graph of applies and their dependencies for execution~
* [ ] in-memory resolver cache for unit tests

## States/Applyables

* [ ] user - create, remove, update, sudoers (#2)
* [ ] group - create, remove (#2)
* [ ] service - enable, disable, start, stop, restart, status (#3)
* [ ] file - create, append, remove, chown, chmod, apply template + data (#10)
* [ ] package - installed, absent, upgrade (#4)
* [ ] exec - execute commands by shelling out (#12)
* [ ] clone - clone code; this is different than a resolver; (#5)

## Resolvers

* [ ] bucket - S3-ish Bucket resolver
* [ ] git - a git resolver; use git checkout; how to configure clone keys?. 

## Variables

* [ ] data - provide a pure data block that turns into a `map[string]string`. This will be good for templates.

## CLI

* do not print subprocess output by default, but let the user get this with a flag
* define a consistent output format, like Salt or Ansible does
* error: red, state changed: blue/green, state unchanged: yellow
* provide a no color mode
* provide a silent "error only" mode
* allow passing a config file straight into stdin
